let number = prompt("Birinchi raqamni kiriting: ");
let number2 = prompt("Birinchi raqamni kiriting: ");
let belgi1 = confirm('* ni bajarsinmi?');
let belgi2 = confirm('/ ni bajarsinmi?');
let belgi3 = confirm('+ ni bajarsinmi?');
let belgi4 = confirm('- ni bajarsinmi?');
console.log( Number(number) * Number(number2) );
console.log( Number(number) / Number(number2) );
console.log( Number(number) + Number(number2) );
console.log( Number(number) - Number(number2) );